# Generated by Django 3.1 on 2020-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='interest_start_date',
            field=models.DateField(blank=True, help_text='The month number that interest calculation will start from', null=True),
        ),
    ]
