# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170817_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Name must be Alphabetic', regex='^[a-zA-Z ]*$')]),
        ),
    ]
